### ISSUE TITLE
Move this repository to the `jenkinsci` GitHub organization

### ISSUE THREAD

**Issue by basil** [jenkinsci/mock-javamail#5]
As part of my work on the Jakarta migration in Jenkins, I am planning to migrate Mailer, Email Extension, and Pipeline: Basic Steps to Jakarta Mail. That in turns depends on updating this library to Jakarta Mail. That in turn depends on refreshing this library.

Refreshing this library would be easiest for me to do if it lived in the `jenkinsci` GitHub organization. If moved, I plan to:

- Update the parent POM to the latest Jenkins parent POM
- Merge #3
- Publish a release to the Jenkins project Artifactory server
- Update Mailer, Email Extension, and Pipeline: Basic Steps to use the new release
- Migrate this library to Jakarta Mail and publish a new release
- Update Mailer, Email Extension, and Pipeline: Basic Steps to use the Jakarta-based version of this library

I am happy to modify this plan if people have other opinions about how we should go about this.

CC @timja

**Comment by timja** [comment]
cc @kohsuke

**Comment by kohsuke** [comment]
All right, sounds like one more project that's graduating from Kohsuke's nest.

Can you confirm that the receiving end approve of the transition?

**Comment by basil** [comment]
This was discussed in [this mailing list thread](https://groups.google.com/g/jenkinsci-dev/c/kZGpxBVq6Sk/m/Jd2ssj7xDwAJ). Jesse and Tim have approved of the plan. I believe Tim is a `jenkinsci` GitHub organization administrator. Once the repository is moved to the `jenkinsci` GitHub organization, I can file my own `repository-permissions-updater` PR to obtain commit and release access.

**Comment by kohsuke** [comment]
There you go. Now the repository is transferred.

**Comment by basil** [comment]
Thank you!
